#!/bin/bash
#
# Slack (slack.com) notification post-receive hook.
#
# Based on: https://github.com/joemiller/git-hooks Campfire notification post-receive hook. Author: Joe Miller
# (http://joemiller.me)
#
# Based on post-receive.irc by Mikael Fridh <frimik@gmail.com> https://gist.github.com/1821358
#
# Settings needed:
#  git config hooks.slack.webhook-url "https://hooks.slack.com/services/..."
#  git config hooks.slack.channel "general"
#
# - The Slack webhook URL can be found in:
#   https://my.slack.com/services/new/incoming-webhook
#
function help() {
  echo "Required config settings:"
  echo " git config hooks.slack.webhook-url 'https://hooks.slack.com/services/...'"
  echo " git config hooks.slack.channel 'general'"
  echo " git config hooks.slack.show-only-last-commit true #optional"
  echo " git config hooks.slack.show-full-commit true #optional"
  echo " git config hooks.slack.username 'git' #optional"
  echo " git config hooks.slack.icon-url 'http://imgur/icon.png' #optional"
  echo " git config hooks.slack.icon-emoji ':twisted_rightwards_arrows:' #optional"
  echo " git config hooks.slack.repo-nice-name 'MyRepo' #optional"
  echo " git config hooks.slack.repos-root '/path/to/repos' #optional"
  echo " git config hooks.slack.changeset-url-pattern 'http://yourserver/%repo_path%/changeset/%rev_hash%' #optional"
  echo " git config hooks.slack.compare-url-pattern 'http://yourserver/%repo_path%/changeset/%old_rev_hash%..%new_rev_hash%' #optional"
  echo " git config hooks.slack.branch-regexp 'regexp'  #optional"
}

function replace_variables() {
  sed "s|%repo_path%|$repopath|g;s|%old_rev_hash%|$oldrev|g;s|%new_rev_hash%|$newrev|g;s|%rev_hash%|$newrev|g;s|%repo_prefix%|$repoprefix|g"
}


function json_string() {
  # takes care of special characters and unicode escapes. assumes
  # input is utf-8 (in practice, every commit message may have a
  # different encoding). invalid utf-8 sequences are replaced
  # ("\ufffd" or "\u00XX" depending on input).
  python -c "import sys, json; print json.dumps(sys.argv[1].decode('utf-8', 'replace'))" "$1"
}

function json_join() {
  local IFS=","
  echo -n "$*";
}

function parse_record() {
  # parse_record STREAMVAR SEPARATOR [FIELDVAR]+
  #
  # Works similarly to the `read` builtin. Instead of using IFS, it
  # splits fields based on the separator given. It reads from and
  # modifies in place variable named STREAMVAR.  Subsequent parameters
  # are variable _names_ used to store tokens, in order.
  #
  # variable STREAMVAR will be advanced by one record: [<FIELD><SEP>]+[\n]*
  #

  local -n stream=$1
  local -n field
  local sep="$2"
  local lf=$'\n' #newline

  shift 2

  # field will point to a different field variable in turn
  for field in "$@"; do
    field="${stream%%${sep}*}"
    # advance stream
    stream="${stream:${#field}}"
    stream="${stream:${#sep}}"
  done
  # eat trailing newlines between records
  while [[ "${stream:0:1}" == $lf ]]; do
    stream=${stream:1}
  done
}

function notify() {
  oldrev=$(git rev-parse $1)
  newrev=$(git rev-parse $2)
  refname="$3"

  # --- Interpret
  # 0000->1234 (create)
  # 1234->2345 (update)
  # 2345->0000 (delete)
  if expr "$oldrev" : '0*$' >/dev/null
  then
    change_type="create"
  else
    if expr "$newrev" : '0*$' >/dev/null
    then
      change_type="delete"
    else
      change_type="update"
    fi
  fi

  # --- Get the revision types
  newrev_type=$(git cat-file -t "$newrev" 2> /dev/null)
  oldrev_type=$(git cat-file -t "$oldrev" 2> /dev/null)
  case "$change_type" in
    create|update)
      rev="$newrev"
      rev_type="$newrev_type"
      ;;
    delete)
      rev="$oldrev"
      rev_type="$oldrev_type"
      ;;
  esac

  # The revision type tells us what type the commit is, combined with
  # the location of the ref we can decide between
  #  - working branch
  #  - tracking branch
  #  - unannoted tag
  #  - annotated tag
  case "$refname","$rev_type" in
    refs/tags/*,commit)
      # un-annotated tag
      refname_type="tag"
      short_refname=${refname##refs/tags/}
      ;;
    refs/tags/*,tag)
      # annotated tag
      refname_type="annotated tag"
      short_refname=${refname##refs/tags/}
      # change recipients
      if [ -n "$announcerecipients" ]; then
        recipients="$announcerecipients"
      fi
      ;;
    refs/heads/*,commit)
      # branch
      refname_type="branch"
      short_refname=${refname##refs/heads/}
      ;;
    refs/remotes/*,commit)
      # tracking branch
      refname_type="tracking branch"
      short_refname=${refname##refs/remotes/}
      echo >&2 "*** Push-update of tracking branch, $refname"
      echo >&2 "***  - no notification generated."
      return 0
      ;;
    *)
      # Anything else (is there anything else?)
      echo >&2 "*** Unknown type of update to $refname ($rev_type)"
      echo >&2 "***  - no notification generated"
      return 0
      ;;
  esac

  branchregexp=$(git config --get hooks.slack.branch-regexp)
  if [ -n "$branchregexp" ]; then
    if [[ ! $short_refname =~ $branchregexp ]]; then
      exit 0;
    fi
  fi

  #channels=$(git config hooks.irc.channel)

  # plural suffix, default "", changed to "s" if commits > 1
  s=""

  # Repo name, either Gitolite or normal repo.
  if [ -n "$GL_REPO" ]; then
    # it's a gitolite repo
    repodir=$(basename "$(pwd)")
    repo=$GL_REPO
  else
    repodir=$(basename "$(pwd)")
    if [ "$repodir" == ".git" ]; then
      repodir=$(dirname "$PWD")
      repodir=$(basename "$repodir")
    fi
    repo=${repodir%.git}
  fi

  repoprefix=$(git config hooks.slack.repo-nice-name || git config hooks.irc.prefix || git config hooks.emailprefix || echo "$repo")
  onlylast=$(git config --get hooks.slack.show-only-last-commit)
  onlylast=$onlylast && [ -n "$onlylast" ]
  fullcommit=$(git config --get hooks.slack.show-full-commit)

  # Get the user information
  # If $GL_USER is set we're running under gitolite.
  if [ -n "$GL_USER" ]; then
    user=$GL_USER
  else
    user=$USER
  fi

  case ${change_type} in
    "create")
      header="New ${refname_type} *${short_refname}* has been created in ${repoprefix}"
      single_commit_suffix="commit"
      ;;
    "delete")
      header="$(tr '[:lower:]' '[:upper:]' <<< ${refname_type:0:1})${refname_type:1} *$short_refname* has been deleted from ${repoprefix}"
      single_commit_suffix="commit"
      ;;
    "update")
      num=$(git log --pretty=oneline ${1}..${2}|wc -l|tr -d ' ')
      branch=${3/refs\/heads\//}

      if [ ${num} -gt 1 ]; then
        header="${num} new commits *pushed* to *${short_refname}* in ${repoprefix}"
        single_commit_suffix="one"
        s="s"
      else
        header="A new commit has been *pushed* to *${short_refname}* in ${repoprefix}"
        single_commit_suffix="one"
      fi

      ;;
    *)
      # most weird ... this should never happen
      echo >&2 "*** Unknown type of update to $refname ($rev_type)"
      echo >&2 "***  - notifications will probably screw up."
      ;;
  esac

  if $onlylast && [[ "${change_type}" != "delete" ]]; then
    header="$header, showing last $single_commit_suffix:"
  fi


  if [[ "${change_type}" != "delete" && "${refname_type}" == "branch" ]]; then
    changeseturlpattern=$(git config --get hooks.slack.changeset-url-pattern)
    compareurlpattern=$(git config --get hooks.slack.compare-url-pattern)
    reporoot=$(git config --get hooks.slack.repos-root)

    urlformat=
    if [ -n "$changeseturlpattern" -a -n "$reporoot" ]; then
      if [[ "$PWD" == ${reporoot}* ]]; then
        repopath=$PWD
        base=$(basename "$PWD")
        if [ "$base" == ".git" ]; then
          repopath=$(dirname $repopath)
        fi
        idx=$(echo "$reporoot" | wc -c | tr -d ' ')
        repopath=$(echo "$repopath" | cut -c$idx-)
        urlformat=$(echo "$changeseturlpattern" | replace_variables)

        if [ -n "$compareurlpattern" ]; then
          comparelink=$(echo "$compareurlpattern" | replace_variables)
	  # insert > after 'new commit(s)'.
	  # we avoid using comparelink on replacement of sed call (because of possible &)
          header=$(echo "$header" | sed -e "s|\([a-zA-Z0-9]\{1,\} new commit[s]\{0,1\}\)\(.*\)|\\1\>\\2|")
	  header="<$comparelink|$header"
        fi
      else
        echo >&2 "$PWD is not in $reporoot. Not creating hyperlinks."
      fi
    fi

    formattedurl=""
    if [ -n "$urlformat" ]; then
      formattedurl="<${urlformat}|%h> "
    fi


    nl="\\\\n"

    if [[ "${change_type}" == "update" ]]; then
      start="${1}"
    else
      start="HEAD"
    fi

    end="${2}"


    # merge `git log` output with $header
    if $onlylast; then
      countarg="-n 1"
    else
      countarg=""
    fi

    # show the full commit message
    if [ "$fullcommit" == "true" ]; then
      commitformat="%s%n%n%b"
    else
      commitformat="%s"
    fi

    sep="boundary-${RANDOM}-${RANDOM}-${RANDOM}-${RANDOM}-${RANDOM}-${RANDOM}-${RANDOM}--"
    log_out=$(git log --pretty=format:"%cN${sep}${formattedurl}${commitformat}${sep}" $countarg "${start}..${end}")
    attachment_arr=()
    while [[ -n "${log_out}" ]]; do
      title=""
      value=""
      parse_record log_out "${sep}" title value

      attachment_arr+=('
{
  "fallback": "",
  "color": "good",
  "fields": [{
    "title": '"$(json_string "$title")"',
    "value": '"$(json_string "$value")"',
    "short": false
  }]
}')
    done


  fi

  if [[ "${#attachment_arr[@]}" -gt 0 ]]; then
    attachments="[ $( json_join "${attachment_arr[@]}" ) ]"
    msg='
"text": '"$(json_string "$header")"',
"attachments": '"$attachments"
  else
    msg='
"text": '"$(json_string "${header}")"
  fi

  webhook_url=$(git config --get hooks.slack.webhook-url)
  channel=$(git config --get hooks.slack.channel)
  username=$(git config --get hooks.slack.username)
  iconurl=$(git config --get hooks.slack.icon-url)
  iconemoji=$(git config --get hooks.slack.icon-emoji)

  if [ -z "$webhook_url" ]; then
    echo "ERROR: config settings not found"
    help
    exit 1
  fi

  payload="{${msg}"

  [[ -z "$channel" ]]   || payload+=',"channel":'"$(json_string "$channel")"
  [[ -z "$username" ]]  || payload+=',"username":'"$(json_string "$username")"
  [[ -z "$iconurl" ]]   || payload+=',"icon_url":'"$(json_string "$iconurl")"
  [[ -z "$iconemoji" ]] || payload+=',"icon_emoji":'"$(json_string "$iconemoji")"

  payload+="}"

  if [ -n "$DEBUG" ]; then
    echo "POST $webhook_url"
    echo "payload=$payload"
    return
  fi

  curl -s \
      --data-urlencode "payload=$payload" \
      "$webhook_url" \
      >/dev/null

}

# MAIN PROGRAM
# Read all refs from stdin, notify slack for each
while read line; do
  set -- $line
  notify $*
  RET=$?
done

exit $RET
